name: tfsec

on:
  push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]  
  # schedule:
  #   - cron: '31 7 * * 3'

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        dir: ["src/aks", "src/core"]
        env: ["prod", "weu-beta", "weu-prod01", "weu-prod02"]

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Check env
        id: check_env
        run: |
          echo "${{ matrix.dir }}/env/${{ matrix.env }}/terraform.tfvars"
          if [ -f "${{ matrix.dir }}/env/${{ matrix.env }}/terraform.tfvars" ]; then
            echo '::set-output name=ENV_EXITS::true'
          else
            echo '::set-output name=ENV_EXITS::false'
          fi

      - name: Run tfsec
        if: steps.check_env.outputs.ENV_EXITS == 'true'
        uses: aquasecurity/tfsec-sarif-action@v0.1.3
        with:
          working_directory: ${{ matrix.dir }}
          sarif_file: ${{ matrix.dir }}/tfsec.sarif
          tfvars_file: ${{ matrix.dir }}/env/${{ matrix.env }}/terraform.tfvars
          # tfsec_version: "v1.27.6"

      - name: Upload SARIF file
        if: steps.check_env.outputs.ENV_EXITS == 'true'
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ matrix.dir }}/tfsec.sarif
          category: ${{ matrix.dir }}_${{ matrix.env }}

      - name: Check sarif
        if: steps.check_env.outputs.ENV_EXITS == 'true'
        run: |
          # cat ${{ matrix.dir }}/tfsec.sarif
          if key=$(jq -re .runs[].results[0].ruleId ${{ matrix.dir }}/tfsec.sarif)
          then
            # If the array was not empty, $key contains the first key
            echo "There are possibile vulnerability"
            echo "Check the report here"
            echo "https://github.com/${{ github.repository }}/security/code-scanning?query=branch%3A${{ github.ref_name }}"
            exit 1
          fi
